export const CREATE_ATTRIBUTE = 'ADD_ATTRIBUTE';
export const EXPAND_ATTRIBUTE = 'EXPAND_ATTRIBUTE';
export const UPDATE_ATTRIBUTE = 'UPDATE_ATTRIBUTE';
export const DELETE_ATTRIBUTE = 'DELETE_ATTRIBUTE';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const ADD_INVALID_ATTRIBUTE = 'ADD_INVALID_ATTRIBUTE';
export const REMOVE_INVALID_ATTRIBUTE = 'REMOVE_INVALID_ATTRIBUTE';
